config/routes.rb
Shouttwo::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :favorites
  resource :settings
  match "/shouts/mine" => "shouts#mine"
  match "/search/:query" => "landing#search"
  resources :shouts do
  end
  root :to => 'landing#index'
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :shout_id, :user_id
  belongs_to :user
  belongs_to :shout
end

app/models/shout.rb
class Shout < ActiveRecord::Base
  attr_accessible :title, :user_id, :media1_content, :media2_content, :media1_type, :media2_type, :compare_type, :tags
  validates :title, 
            :presence => true, 
            :length => { :maximum => 50, :minimum => 1 }
  validates :user_id, :presence => true
  validates :media1_type, 
            :inclusion => { :in => %w(video picture text)}
  validates :media1_content, 
            :presence => true,
            :length => { :maximum => 100, :minimum => 1 }
  validates :media2_type, :presence => true,
            :inclusion => { :in => %w(video picture text)}
  validates :media2_content, 
             :presence => true,
            :length => { :maximum => 100, :minimum => 1 }
  belongs_to :user
  has_many :favorites
  delegate :username, :to => :user
  has_many :views

  define_index do
    indexes title
    indexes media1_content
    indexes media2_content

    has user_id, created_at, updated_at
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  has_many :shouts
  has_many :favorites
  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = User.where(:email => data.email).first
      user
    else # Create a user with a stub password. 
      User.create!(:email => data.email, :password => 'temp_facebook') 
    end
  end
end

app/models/view.rb
class View < ActiveRecord::Base
  attr_accessible :session_id, :shout_id 
  belongs_to :shout,
            :counter_cache => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :assign_current_user

  private
  def assign_current_user
    @current_user = current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    Favorite.create({:user_id => current_user.id, :shout_id => params[:shout_id]})
    shout = Shout.find(params[:shout_id])
    shout.increment!(:num_favorites)
    render :nothing => true
  end

  def destroy
    Favorite.destroy_all({:user_id => current_user.id, :shout_id => params[:id]})
    shout = Shout.find(params[:id])
    shout.decrement!(:num_favorites)
    render :nothing => true
  end

  def index 
    shout_ids = Favorite.where(:user_id => current_user.id).map(&:shout_id)
    @shouts = Shout.where(:id => shout_ids)
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @sort = params[:sort]
    if @sort == "views"
      @shouts = Shout.limit(5).order("views desc")
    elsif @sort == "favorites"
      @shouts = Shout.limit(5).order("num_favorites desc") 
    else
      @shouts = Shout.limit(5).order("created_at desc")
    end
      
    @user = current_user
    if current_user
      @favorite_shout_ids = current_user.favorites.collect(&:shout_id)
    else
      @favorite_shout_ids = nil
    end
  end

  def search
    @user = current_user
    if current_user
      @favorite_shout_ids = current_user.favorites.collect(&:shout_id)
    else
      @favorite_shout_ids = nil
    end
    @search_term = params[:query]
    @shouts = Shout.search @search_term
  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def edit 
    @user = current_user
  end

  def update
    @user = User.find(current_user.id)
    if @user.update_attributes(params[:user])
      sign_in @user, :bypass => true
      redirect_to new_shout_path
    else
      render "edit"
    end
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  include ShoutsHelper
  before_filter :authenticate_user!, :only => [:create, :new]
  before_filter :check_username, :only => [:create, :new]
  respond_to :html

  def show
    @shout = Shout.find(params[:id])
    view = View.where(:session_id => request.session_options[:id], :shout_id => params[:id])
    if view.empty?
      View.create!(:session_id => request.session_options[:id], :shout_id => params[:id])
     end 
    if current_user
      @favorite_shout_ids = current_user.favorites.collect(&:shout_id)
    else
      @favorite_shout_ids = nil
    end
  end

  def create
    shout_params = params[:shout] 
    shout_params[:user_id] = current_user.id
    @shout = Shout.new(params[:shout])
    @shout.save
    respond_with @shout
  end

  def new
    @shout = Shout.new
  end

  def edit
  end

  def mine
    @shouts = current_user.shouts
    @mine = true
  end

  private

  def check_username
    redirect_to :edit_settings unless current_user.username 
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/shouts_helper.rb
module ShoutsHelper
  def youtube_embed(youtube_url, width)
    if youtube_url[/youtu\.be\/([^\?]*)/]
      youtube_id = $1
    else
      youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      youtube_id = $5
    end
    %Q{<iframe title="YouTube video player" width="#{ width }" height="#{ width}" src="http://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>} 
  end

  def compare_type_convert(compare_type)
    if compare_type == "greater_than"
      return_compare = '>'  
    elsif compare_type == "less_than"
      return_compare = '<'
    else
      return_compare = '='
    end
    return_compare
  end
end

app/views/favorites/index.html.erb
<div class="container" style="padding-top: 10px">
  <div class="row">
    <div id="content" class="span12">
      <div>
        <div class="row">
          <div class="span12">
            <h1>My Favorites</h1>
            <div id="content-box">
              <%= render :partial => 'shouts/shout_list', :collection => @shouts, :as => :shout || 'There are no shouts available.' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/landing/_content.html.erb
<div id="content-box">
  <div class="row" style="padding-bottom: 10px; border-bottom: 1px solid #DDDDDD">
    <div class="span4" style="margin-left:30px">
      <img src="assets/mock/lin.jpg" width="300">
    </div>
    <div class="span1" style="margin-top:80px;font-size:100px">
      > 
    </div>
    <div class="span4" style="margin-left:10px">
      <img src="assets/mock/kobe.jpg" width="300">
    </div>
    <div class="span3" style="margin-left:5px">
      <div id="share-box" style="border-radius: 1px 1px 1px 1px; box-shadow: 0 1px 2px #AAAAAA; padding-top: 5px;"> 
        <h3>Jeremy Lin vs Kobe Bryant</h3>
        <div><a href="#"> James </a></div>
        <i class="icon-eye-open"></i>100
        <i class="icon-check"></i>10
        <br/>
        <br/>
        <a class="btn btn-large" href="#">
          <i class="icon-comment"></i>
          Comment
        </a>
        <a class="btn btn-large" href="#">
          <i class="icon-check"></i>
          Favorite
        </a>
        <br/>
        <br/>
        <iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.google.com&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=true&amp;action=recommend&amp;colorscheme=light&amp;font=lucida+grande&amp;height=21&amp;appId=152460108176191" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:21px;" allowTransparency="true"></iframe>
      </div>
    </div>
  </div>
</div>

app/views/landing/_content_header.html.erb
<div id="content-header">
  <div class="top-bar">
    <ul class="nav nav-tabs">
      <li <%= 'class=active' if (@sort == "recent" || @sort.nil?) %>>
      <a href="/shouttwo?sort=recent">Recent</a>
      </li>
      <li <%= 'class=active' if @sort == "views" %>>
        <a href="/shouttwo?sort=views">
        Views 
        </a>
      </li>
      <li <%= 'class=active' if @sort == "favorites" %>>
        <a href="/shouttwo?sort=favorites">
          Liked 
        </a>
      </li>
    </ul>
  </div>
</div>

app/views/landing/_hero_unit.html.erb
<div class="hero-unit">
  <i id="hero-unit-remove-icon" class="icon-remove" style = "float:right; margin-right: -20px; margin-top:-20px;"></i>
  <h2>Welcome to Shout Two ! </h2>
  <p> &nbsp;</p>
  <img width="300px" height="200px" style="float:left;padding-top:50px;" src="assets/logo.png">
  <p style="padding-top:0px;padding-left:340px;">
    This is an app for shouting out media!  You can 
    <a href="#">Create</a>
    shouts to express yourself.  You can also 
    <a href="#">View</a>
    shouts to view what others have created.
    <br/>
    <br/>
    <a class="btn btn-primary btn-large" href="#">Learn more ></a>
  </p>
</div>

app/views/landing/_shout.html.erb
<div class="row" style="padding-top: 10px; padding-bottom: 10px; border-bottom: 1px solid #DDDDDD">
  <div class="span4" style="margin-left:30px">
    <%= render :partial => "landing/media", :locals => {:type => shout.media1_type, :content => shout.media1_content, :width => '300'}%>
  </div>
  <div class="span1" style="margin-top:80px;font-size:100px">
    <%= compare_type_convert(shout.compare_type)%>
  </div>
  <div class="span4" style="margin-left:10px">
    <%= render :partial => "landing/media", :locals => {:type => shout.media2_type, :content => shout.media2_content, :width => '300'}%>
  </div>
  <div class="span3" style="margin-left:5px">
    <div id="share-box" style="border-radius: 1px 1px 1px 1px; box-shadow: 0 1px 2px #AAAAAA; padding-top: 5px;"> 
      <h3><%= shout.title %></h3>
      <div><a href="#"> <%= shout.user_id %></a></div>
      <i class="icon-eye-open"></i><%= shout.views %>
      <i class="icon-check"></i><%= shout.favorites %>
      <br/>
      <br/>
      <a class="btn btn-large" href="#">
        <i class="icon-comment"></i>
        Comment
      </a>
      <a class="btn btn-large" href="#">
        <i class="icon-check"></i>
        Favorite
      </a>
      <br/>
      <br/>
      <iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.google.com&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=true&amp;action=recommend&amp;colorscheme=light&amp;font=lucida+grande&amp;height=21&amp;appId=152460108176191" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:21px;" allowTransparency="true"></iframe>
    </div>
  </div>
</div>

app/views/landing/index.html.erb
<div class="container" style="padding-top: 10px">
  <div class="row">
    <div id="content" class="span12">
      <div>
        <%= render "hero_unit" %>
        <div class="row">
          <div class="span12">
            <%= render "content_header" %>
            <div id="content-box">
              <%= render :partial => 'shouts/shout_list', :collection => @shouts, :as => :shout || 'There are no shouts available.' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/landing/search.html.erb
<div class="container" style="padding-top: 10px">
  <div class="row">
    <div id="content" class="span12">
      <div>
        <div class="row">
          <div class="span12">
            Your search for <%= @search_term %>
            <div id="content-box">
              <%= render :partial => 'shouts/shout_list', :collection => @shouts, :as => :shout || 'There are no shouts available.' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/shouttwo">ShoutTwo</a>
      <form class="navbar-search pull-left">
        <input id="landing-search-box" type="text" class="search-query" placeholder="Search">
      </form>
      <ul class="nav">
        <li class="active">
          <a href="http://www.jamesjn.com/shouttwo?sort=recent">Recent</a>
        </li>
        <li>
          <a href="http://www.jamesjn.com/shouttwo?sort=views">Popular</a>
        </li>
        <li>
          <a href="http://www.jamesjn.com/shouttwo?sort=favorites">Liked</a>
        </li>
        <li>
          <a href="/shouttwo/shouts/new">Create Shout</a>
        </li>
      </ul>
      <ul class="nav pull-right">
        <li>
          <% if @current_user %>
            <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">
              <span style="color: #999999"> Hello <%= @current_user.username || @current_user.email %> </span>
              <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="http://www.jamesjn.com/shouttwo/favorites">Favorites</a></li>
                <li><a href="http://www.jamesjn.com/shouttwo/shouts/mine">My Shouts</a></li>
                <li><a href="http://www.jamesjn.com/shouttwo/settings/edit">My Profile</a></li>
                <li class="divider"></li>
                <li> <%= link_to "Log out", destroy_user_session_path, :method => :delete %> <li>
              </ul>
            </li>
          <% else %>
            <%= link_to "Login", user_omniauth_authorize_path(:facebook), :class => "btn" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shouttwo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", 'bootstrap-dropdown', 'bootstrap-button' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=152460108176191";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<p class="notice"><%= notice %></p>
<p class="devise_alert"><%= alert %></p>
<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>

app/views/settings/edit.html.erb
<h2>Please chooose a username and password</h2>

<%= form_for(@user, :url => settings_path) do |f| %>

  <div><%= f.label :username %><br />
  <%= f.text_field :username %></div>

  <div><%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

  <div><%= f.submit "Update" %></div>
<% end %>
<%= link_to "Back", :back %>

app/views/shouts/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'jamesjn'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/shouts/_info.html.erb
<div id="share-box" style="border-radius: 1px 1px 1px 1px; box-shadow: 0 1px 2px #AAAAAA; padding-top: 5px;"> 
  <div class="art-clickable" data-shout="<%=shout.id %>" > <h3><a style="color:black"><%= shout.title %></a></h3></div>
  <div> <a href="#"> <%= shout.username || ''%></a></div>
  <i class="icon-eye-open"></i><%= shout.views_count %>
  <i class="icon-heart"></i><%= shout.num_favorites %>
  <br/>
  <br/>
  <a class="btn btn-large art-clickable" data-shout="<%=shout.id %>">
    <i class="icon-comment"> </i>
    Comment
  </a>
  <% if @favorite_shout_ids %>
    <% if @favorite_shout_ids.include?(shout.id) %>
      <a data-shout-id="<%=shout.id%>" class="btn btn-large favorited yellow">
        <i class="icon-heart"></i>
        Favorite
      </a>
    <% else %>
      <a data-shout-id="<%=shout.id%>" class="btn btn-large not-favorited">
        <i class="icon-check"></i>
        Favorite
      </a>
    <% end %>
  <% end %>
  <br/>
  <br/>
  <div class="fb-like" data-href="http://www.jamesjn.com/shouttwo/shouts/#{shout.id}" data-send="true" data-layout="button_count" data-width="300" data-show-faces="false"></div>
</div>

app/views/shouts/_media.html.erb
<% if type == "picture" %>
  <img src="<%= content %>" width="<%= width %>"/>
<% elsif type == "video" %>
  <%= (youtube_embed content, width).html_safe %>
<% elsif type == "text" %>
  <%= h content%>
<% end %>

app/views/shouts/_shout.html.erb
<div style="border-bottom: 1px solid #DDDDDD">
  <%= render :partial => 'shout_header', :locals => {:shout => shout} %>
</div>
<div class="row" data-shout="<%=shout.id %>" style="min-height: 200px;padding-top: 10px; padding-bottom</h4></div>: 10px; border-bottom: 1px solid #DDDDDD">
  <div class="span5" style="margin-left:30px">
    <%= render :partial => "shouts/media", :locals => {:type => shout.media1_type, :content => shout.media1_content, :width => '450'}%>
  </div>
  <div class="span1" style="margin-top:80px;font-size:100px">
    <%= compare_type_convert(shout.compare_type)%>
  </div>
  <div class="span5" style="margin-left:10px">
    <%= render :partial => "shouts/media", :locals => {:type => shout.media2_type, :content => shout.media2_content, :width => '450'}%>
  </div>
</div>
<%= render 'disqus' %>

app/views/shouts/_shout_header.html.erb
<div><h3> <%=shout.title || '' %> </h3></div>
<div>
  <h4> 
    @<%=shout.username || ''%> |
    <i class="icon-eye-open"></i><%= shout.views_count %>
    <i class="icon-heart"></i><%= shout.num_favorites %>
  </h4>
  <% if @favorite_shout_ids %>
    <% if @favorite_shout_ids.include?(shout.id) %>
      <a data-shout-id="<%=shout.id%>" class="btn btn-large favorited yellow">
        <i class="icon-heart"></i>
        Favorite
      </a>
    <% else %>
      <a data-shout-id="<%=shout.id%>" class="btn btn-large not-favorited">
        <i class="icon-check"></i>
        Favorite
      </a>
    <% end %>
  <% end %>
  <div class="fb-like" data-href="http://www.jamesjn.com/shouttwo/shouts/" data-send="true" data-layout="button_count" data-width="300" data-show-faces="false"></div>
</div>

app/views/shouts/_shout_list.html.erb
<div class="row" style="padding-top: 10px; padding-bottom: 10px; border-bottom: 1px solid #DDDDDD">
  <div class="span4 art-clickable" data-shout="<%=shout.id %>" style="margin-left:30px">
    <%= render :partial => "shouts/media", :locals => {:type => shout.media1_type, :content => shout.media1_content, :width => '300'}%>
  </div>
  <div class="span1" style="margin-top:80px;font-size:100px">
    <%= compare_type_convert(shout.compare_type)%>
  </div>
  <div class="span4 art-clickable" data-shout="<%=shout.id %>" style="margin-left:10px">
    <%= render :partial => "shouts/media", :locals => {:type => shout.media2_type, :content => shout.media2_content, :width => '300'}%>
  </div>
  <div class="span3" style="margin-left:5px">
    <%= render :partial => 'shouts/info', :locals => {:shout => shout} %>
  </div>
</div>

app/views/shouts/mine.html.erb
<div class="container" style="padding-top: 10px">
  <div class="row">
    <div id="content" class="span12">
      <div>
        <div class="row">
          <div class="span12">
            <h1>My Shouts</h1>
            <div id="content-box">
              <%= render :partial => 'shouts/shout_list', :collection => @shouts, :as => :shout || 'There are no shouts available.' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shouts/new.html.erb
<div class="container" style="padding-top:20px; width: 750px;">
  <div id="content-header">
    <div class="top-bar" style="padding: 10px; ">
      <div class="row">
        <div class="span3">
          <h1>Add a shout</h1>
        </div>
        <div class="span2" >
          Type of media 1:
          <div class="btn-group" data-toggle="buttons-radio">
            <button id="media1-picture-button" class="btn" data-toggle="button">
              <i class="icon-picture"></i>
            </button>
            <button id="media1-video-button" class="btn">
              <i class="icon-facetime-video"></i>
            </button>
            <button id="media1-text-button" class="btn">
              <i class="icon-pencil"></i>
            </button>
          </div>
        </div>
        <div class="span2" >
          Type of media 2:
          <div class="btn-group" data-toggle="buttons-radio">
            <button id="media2-picture-button" class="btn" data-toggle="button">
              <i class="icon-picture"></i>
            </button>
            <button id="media2-video-button" class="btn">
              <i class="icon-facetime-video"></i>
            </button>
            <button id="media2-text-button" class="btn">
              <i class="icon-pencil"></i>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="content-box" style="min-height:400px" >
    <div id="shout_form" style="padding: 10px; font-size: 20px;">
      <%= form_for(@shout) do |shout_form| %>
        <% if @shout.errors.any? %>
          <div id="errorExplanation" class="alert block_message warning">
            <a class="close" data-dismiss="alert">x</a>
            <% @shout.errors.messages.each do |msg| %>
              <p><%= msg[0].to_s + ": " + msg[1].join(" and ") %></p>
            <% end %>
          </div>
        <% end %>
        <div class="row">
          <div class="span2">
            Shout Title
          </div>
          <div class="span7">
            <%= shout_form.text_field :title, :class => "span7", :style => "height: 30px; font-size: 30px"%>
          </div>
        </div>

        <div class="row" style="padding-top: 30px">
          <div id="media1-label" class="span2">
            Picture 1 URL 
          </div>
          <div class="span7">
            <%= shout_form.text_field :media1_content, :class => "span7", :style => "height: 30px; font-size: 30px; margin-bottom:0px;"%>
            <%= shout_form.hidden_field :media1_type, :value => "picture"%>
            <div id="imgur_upload1" style="font-size:15px;height:15px;">
              <a onclick="$('#shout1_uploader').click()">Upload to imgur</a>
              <input id="shout1_uploader" type="file" style="display:none" onchange="upload(this.files[0], '#shout_media1_content')">
            </div>
          </div>
        </div>

        <div class="row" style="padding-top: 20px">
          <div id="media2-label" class="span2">
            Picture 2 URL 
          </div>
          <div class="span7">
            <%= shout_form.text_field :media2_content, :class => "span7", :style => "height: 30px; font-size: 30px; margin-bottom:0px;"%>
            <%= shout_form.hidden_field :media2_type, :value => "picture"%>
            <div id="imgur_upload2" style="font-size:15px;height:15px;">
              <a onclick="$('#shout2_uploader').click()">Upload to imgur</a>
              <input id="shout2_uploader" type="file" style="display:none" onchange="upload(this.files[0], '#shout_media2_content')">
            </div>
          </div>
        </div>

        <div class="row" style="padding-top: 20px">
          <div class="span2">
            Tags 
          </div>
          <div class="span7">
            <%= shout_form.text_field :tags, 
                :class => "span7", 
                :style => "height: 30px; font-size: 30px"%>
          </div>
        </div>

        <div class="row" style="padding-top: 30px; padding-bottom:20px; border-bottom: 1px solid #DDDDDD;">
          <div class="span2">
            Compare
          </div>
          <div class="span7" style="font-size:40px">
            <div class="btn-group" data-toggle="buttons-radio">
              <%= shout_form.radio_button :compare_type, 
                  "greater_than" %> >
              <%= shout_form.radio_button :compare_type, 
                  "equal", 
                  :checked => true %> = 
              <%= shout_form.radio_button :compare_type, 
                  "less_than" %> <
            </div>
          </div>
        </div>

        <div class="row" style="padding-top: 20px; padding-right:10px;">
          <span style="float:right">
            <%= shout_form.submit "Create", :class => "btn btn-primary btn-large" %>
          </span>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/shouts/show.html.erb
<div class="container" style="padding-top: 10px">
  <div class="row">
    <div id="content" class="span12">
      <div class="row">
        <div class="span12">
          <div id="content-box">
            <%= render :partial => 'shouts/shout', :locals => {:shout => @shout} %> 
          </div>
        </div>
      </div>
    </div>
  </div>
</div>